enum estado_completo_em_progresso_cancelado_pendente_t {
	completo
	em_progresso
	cancelado
	pendente
}

enum estado_recusado_aceito_pendente_t {
	recusado
	aceito
	pendente
}

Table tbl_prestador [headercolor: #175e7a] {
	id varchar(255) [ pk, not null, unique ]
	profissao varchar(100) [ not null ]
	preco_ora numeric [ not null ]
	minimo_Desconto decimal(10, 2)
	porcentage_Desconto decimal(10, 2)
	taxa_Uregencia decimal(10, 2)
	nif numeric [ not null ]
	enabled_at boolean [ not null ]
	creatde_at datetime
	updated_at datetime
}

Table tbl_users [headercolor: #175e7a] {
	id varchar(255) [ pk, not null, unique ]
	nome varchar(50) [ not null ]
	numero_especificacao varchar(100) [ not null, unique ]
	data_nas date [ not null ]
	email varchar(100) [ not null ]
	contacto varchar(255)
	pais varchar(100) [ not null ]
	localidade varchar(100) [ not null ]
	passwords varchar(255)
	enabled_at boolean [ not null ]
	created_at datetime [ not null ]
	updated_at datetime [ not null ]
}

Table tbl_orcamento [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	id_users varchar(255) [ not null ]
	total double [ not null ]
	enabled_at boolean [ not null ]
	created_at datetime [ not null ]
	updated_at datetime [ not null ]
}

Table tbl_servicos [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	nome varchar(50) [ not null ]
	descricao varchar(255)
	categoria varchar(20) [ not null ]
	enabled_at boolean [ not null ]
	created_at datetime [ not null ]
	updated_time datetime [ not null ]
}

Table tbl_prestacao_de_servicos [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	id_prestador varchar(255) [ not null ]
	id_servico integer [ not null ]
	id_orcamento integer [ not null ]
	designacao varchar(100) [ not null ]
	subtotal double [ not null ]
	horas_estimadas integer
	preco_hora double
	estado estado_completo_em_progresso_cancelado_pendente_t [ not null ]
	enabled_at boolean [ not null ]
	created_at datetime [ not null ]
	updated_at datetime [ not null ]
}

Table tbl_proposta [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	id_prestacao_servico integer [ not null ]
	preco_hora double [ not null ]
	horas_estimadas integer [ not null ]
	estado estado_recusado_aceito_pendente_t [ not null ]
	enebled_at boolean [ not null ]
	creted_at datetime
	updated_at datetime
}

Ref fk_tbl_orcamento_id_users_tbl_users {
	tbl_orcamento.id_users > tbl_users.id [ delete: no action, update: no action ]
}

Ref fk_tbl_prestador_id_tbl_prestacao_de_servicos {
	tbl_prestador.id < tbl_prestacao_de_servicos.id_prestador [ delete: no action, update: no action ]
}

Ref fk_tbl_servicos_id_tbl_prestacao_de_servicos {
	tbl_servicos.id < tbl_prestacao_de_servicos.id_servico [ delete: no action, update: no action ]
}

Ref fk_tbl_orcamento_id_tbl_prestacao_de_servicos {
	tbl_orcamento.id < tbl_prestacao_de_servicos.id_orcamento [ delete: no action, update: no action ]
}

Ref fk_tbl_prestacao_de_servicos_id_tbl_proposta {
	tbl_prestacao_de_servicos.id < tbl_proposta.id_prestacao_servico [ delete: no action, update: no action ]
}